name: Auto-refresh

on:
  workflow_dispatch:          # manual trigger button
  schedule:
    - cron: "0 */3 * * *"     # every 3 h (00,03,06… UTC)

# NEW: allow the workflow to push commits back to the repo
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run python generator.py
        run: python generator.py
